name: Build and publish image to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  publish_images:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose
    
    - name: Build the containers
      run: docker-compose -f docker-compose-prod.yml build

    - name: Set up a unique tag
      run: echo "TAG=${{ github.sha }}" >> $GITHUB_ENV

    - name: Tag images for Google Container Registry
      run: |
        docker tag arqweb-tp1_backend gcr.io/${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}/arqweb-tp1_backend:${{ env.TAG }}
        docker tag arqweb-tp1_frontend gcr.io/${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}/arqweb-tp1_frontend:${{ env.TAG }}

    - name: Set up Google Cloud Authentication
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GOOGLE_CLOUD_CREDENTIALS_JSON }}
        
    - name: Push images to Google Container Registry
      run: |
        docker push gcr.io/${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}/arqweb-tp1_backend:${{ env.TAG }}
        docker push gcr.io/${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}/arqweb-tp1_frontend:${{ env.TAG }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}

    - name: Deploy to Google Cloud Run
      run: |
        gcloud run deploy arqweb-tp1-backend \
          --image gcr.io/${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}/arqweb-tp1_backend:${{ github.sha }} \
          --platform managed \
          --region ${{ secrets.GOOGLE_CLOUD_PROJECT_REGION }} \
          --allow-unauthenticated

        gcloud run deploy arqweb-tp1-frontend \
          --image gcr.io/${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}/arqweb-tp1_frontend:${{ github.sha }} \
          --platform managed \
          --region ${{ secrets.GOOGLE_CLOUD_PROJECT_REGION }} \
          --allow-unauthenticated
