name: Build and publish image to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  publish_images:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose
    - name: build
      run: docker-compose -f docker-compose-prod.yml build

    - name: Tag images for Docker Hub
      run: |
        docker tag arqweb-tp1_backend ${{ secrets.DOCKER_HUB_USERNAME }}/arqweb-tp1_backend:latest
        docker tag arqweb-tp1_frontend ${{ secrets.DOCKER_HUB_USERNAME }}/arqweb-tp1_frontend:latest
      
    - name: push image to docker hub
    
      run: |
        docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_TOKEN }}
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/arqweb-tp1_backend:latest
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/arqweb-tp1_frontend:latest

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        service_account_key: ${{ secrets.GOOGLE_CLOUD_SERVICE_ACCOUNT_KEY }}
        project_id: ${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}
        export_default_credentials: true

    - name: Deploy to Google Cloud
      run: |
        gcloud run deploy arqweb-tp1-backend \
          --image ${{ secrets.DOCKER_HUB_USERNAME }}/arqweb-tp1_backend:latest \
          --platform managed \
          --region ${{ secrets.GOOGLE_CLOUD_PROJECT_REGION }} \
          --allow-unauthenticated
        
        gcloud run deploy arqweb-tp1-frontend \
          --image ${{ secrets.DOCKER_HUB_USERNAME }}/arqweb-tp1_frontend:latest \
          --platform managed \
          --region ${{ secrets.GOOGLE_CLOUD_PROJECT_REGION }} \
          --allow-unauthenticated
