name: Docker Compose CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Compose
      run: sudo apt-get install docker-compose
    - name: Build and run services
      run: docker-compose up --build -d
    - name: Shut down services
      run: docker-compose down
